# Generated by Django 5.2.6 on 2025-09-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_attendance_section'),
        ('exams', '0002_remove_exam_section'),
        ('sections', '0001_initial'),
        ('students', '0002_remove_student_section'),
        ('timetable', '0002_remove_timetable_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
