# Generated by Django 5.2.6 on 2025-09-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_subject_classsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
